import { AuthRecord } from './types';

export const mockAuthRecords: AuthRecord[] = [
  {
    id: '1',
    patient: { name: 'Pepe Johnson', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_6000',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'Authorized',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Follow-up'],
    notes: 'Submitted request via availity - 3/12 3:45pm',
    confidence: 'Confirmed',
  },
  {
    id: '2',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_48231',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'Authorized',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['OT'],
    notes: 'Submitted request via availity - 3/12 3:45pm',
    confidence: 'Confirmed',
  },
  {
    id: '3',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_48231',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'Not Started',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['SLP'],
    notes: 'Submitted request via availity - 3/12 3:45pm',
  },
  {
    id: '4',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_48231',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'Pending Payer Response',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Urgent'],
    notes: 'Submitted request via availity - 3/12 3:45pm',
  },
  {
    id: '5',
    patient: { name: 'Xavier Nielson', dob: '06/14/1998', mrn: 'MRN-00291-5513' },
    authNumber: 'AUTH-AET_5000',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '3/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'In Progress',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['OT', 'New'],
    notes: 'Submitted request via availity - 3/12 3:45pm',
    confidence: 'Confirmed',
  },
  {
    id: '6',
    patient: { name: 'Maria Chen', dob: '03/22/1985', mrn: 'MRN-00312-8841' },
    authNumber: 'AUTH-UHC_7721',
    payer: { name: 'UHC', planId: '00445' },
    startDate: '1/15',
    endDate: '3/15',
    visitsAuthorized: 12,
    visitsCompleted: 12,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['PT'],
    notes: 'Auth expired - renewal needed',
  },
  {
    id: '7',
    patient: { name: 'Robert Kim', dob: '11/08/1972', mrn: 'MRN-00456-1123' },
    authNumber: 'AUTH-AET_9102',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '3/01',
    endDate: '5/01',
    visitsAuthorized: 30,
    visitsCompleted: 8,
    visitsScheduled: 2,
    state: 'Auth Requested',
    status: 'Expiring Soon',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['SLP', 'Review'],
    notes: 'Awaiting response from payer since 4/10',
    confidence: 'Pending',
  },
  {
    id: '8',
    patient: { name: 'Aisha Patel', dob: '07/19/1990', mrn: 'MRN-00578-3394' },
    authNumber: '',
    payer: { name: 'Cigna', planId: '00187' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 3,
    visitsScheduled: 1,
    state: 'Not Started',
    status: 'Needs Auth',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['OT', 'Urgent'],
    notes: 'Patient started treatment without auth on file',
  },
];
