import type { AuthRecord } from './types';

export const mockAuthRecords: AuthRecord[] = [
  {
    id: '1',
    patient: { name: 'Pepe Johnson', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_6000',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'Authorized',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Follow-up'],
    notes: [
      { id: 'n1a', text: 'Submitted request via availity', author: 'Jonathon Zuniga', timestamp: '2026-03-12T15:45:00' },
      { id: 'n1b', text: 'Received request for more documentation', author: 'Jake Pellegrini', timestamp: '2026-03-13T16:45:00' },
      { id: 'n1c', text: 'Submitted requested documentation', author: 'Jake Pellegrini', timestamp: '2026-03-13T17:30:00' },
    ],
    timeline: [
      { id: 'tl-1a', timestamp: '2026-03-12T15:45:00', author: 'Jonathon Zuniga', action: { kind: 'note_added', text: 'Submitted request via availity' } },
      { id: 'tl-1b', timestamp: '2026-03-13T10:00:00', author: 'Adam Smith', action: { kind: 'detail_changed', field: 'Assigned To', from: 'Unassigned', to: 'Jaime Mandela' } },
      { id: 'tl-1c', timestamp: '2026-03-13T16:45:00', author: 'Jake Pellegrini', action: { kind: 'note_added', text: 'Received request for more documentation' } },
      { id: 'tl-1d', timestamp: '2026-03-13T17:30:00', author: 'Jake Pellegrini', action: { kind: 'note_added', text: 'Submitted requested documentation' } },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '2',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: '',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 0,
    visitsScheduled: 0,
    state: 'Not Started',
    status: 'Needs Auth',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['OT'],
    notes: [],
  },
  {
    id: '3',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_4001',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/28',
    endDate: '12/31',
    visitsAuthorized: 20,
    visitsCompleted: 21,
    visitsScheduled: 2,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['SLP'],
    notes: [
      { id: 'n3a', text: 'Previous auth - fully utilized', author: 'Emma Smith', timestamp: '2026-01-15T10:00:00' },
    ],
    timeline: [
      { id: 'tl-3a', timestamp: '2026-01-15T10:00:00', author: 'Emma Smith', action: { kind: 'note_added', text: 'Previous auth - fully utilized' } },
      { id: 'tl-3b', timestamp: '2026-02-28T09:00:00', author: 'Adam Smith', action: { kind: 'detail_changed', field: 'Start Date', from: '--', to: '2/28' } },
      { id: 'tl-3c', timestamp: '2026-03-20T14:00:00', author: 'Jaime Mandela', action: { kind: 'detail_changed', field: 'End Date', from: '6/30', to: '12/31' } },
    ],
  },
  {
    id: '4',
    patient: { name: 'Diana Morales', dob: '06/14/1998', mrn: 'MRN-00184-2297' },
    authNumber: 'AUTH-AET_4000',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '11/01',
    endDate: '1/15',
    visitsAuthorized: 15,
    visitsCompleted: 15,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT'],
    notes: [
      { id: 'n4a', text: 'Initial auth - completed', author: 'Jaime Mandela', timestamp: '2025-11-01T09:00:00' },
    ],
  },
  {
    id: '5',
    patient: { name: 'Xavier Nielson', dob: '06/14/1998', mrn: 'MRN-00291-5513' },
    authNumber: 'AUTH-AET_5000',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '3/28',
    endDate: '4/28',
    visitsAuthorized: 20,
    visitsCompleted: 14,
    visitsScheduled: 3,
    state: 'In Progress',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['OT', 'New'],
    notes: [
      { id: 'n5a', text: 'Submitted request via availity', author: 'Jonathon Zuniga', timestamp: '2026-03-12T15:45:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '6',
    patient: { name: 'Maria Chen', dob: '03/22/1985', mrn: 'MRN-00312-8841' },
    authNumber: 'AUTH-UHC_7721',
    payer: { name: 'UHC', planId: '00445' },
    startDate: '1/15',
    endDate: '3/15',
    visitsAuthorized: 12,
    visitsCompleted: 12,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['PT'],
    notes: [
      { id: 'n6a', text: 'Auth expired - renewal needed', author: 'Emma Smith', timestamp: '2026-03-16T11:00:00' },
    ],
  },
  {
    id: '7',
    patient: { name: 'Robert Kim', dob: '11/08/1972', mrn: 'MRN-00456-1123' },
    authNumber: 'AUTH-AET_9102',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '3/01',
    endDate: '5/01',
    visitsAuthorized: 30,
    visitsCompleted: 8,
    visitsScheduled: 2,
    state: 'Auth Requested',
    status: 'Expiring Soon',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['SLP', 'Review'],
    notes: [
      { id: 'n7a', text: 'Awaiting response from payer since 4/10', author: 'Jaime Mandela', timestamp: '2026-04-10T14:20:00' },
      { id: 'n7b', text: 'Follow-up call placed to Aetna rep', author: 'Jaime Mandela', timestamp: '2026-04-15T09:15:00' },
    ],
    confidence: 'Pending',
  },
  {
    id: '8',
    patient: { name: 'Aisha Patel', dob: '07/19/1990', mrn: 'MRN-00578-3394' },
    authNumber: '',
    payer: { name: 'Cigna', planId: '00187' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 3,
    visitsScheduled: 1,
    state: 'Not Started',
    status: 'Needs Auth',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['OT', 'Urgent'],
    notes: [
      { id: 'n8a', text: 'Patient started treatment without auth on file', author: 'Dr. Li', timestamp: '2026-04-18T10:00:00' },
    ],
  },
  {
    id: '9',
    patient: { name: 'Marcus Thompson', dob: '02/17/1965', mrn: 'MRN-00623-4410' },
    authNumber: 'AUTH-UHC_3345',
    payer: { name: 'UHC', planId: '00445' },
    startDate: '3/10',
    endDate: '5/10',
    visitsAuthorized: 24,
    visitsCompleted: 18,
    visitsScheduled: 4,
    state: 'Authorized',
    status: 'Expiring Soon',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Post-Op'],
    notes: [
      { id: 'n9a', text: 'Post-op knee replacement rehab', author: 'Sarah Adams', timestamp: '2026-03-10T09:00:00' },
      { id: 'n9b', text: 'Patient progressing well, may need extension', author: 'Sarah Adams', timestamp: '2026-04-05T14:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '10',
    patient: { name: 'Lily Tran', dob: '09/03/2001', mrn: 'MRN-00701-8823' },
    authNumber: 'AUTH-CIG_1182',
    payer: { name: 'Cigna', planId: '00187' },
    startDate: '4/01',
    endDate: '6/01',
    visitsAuthorized: 16,
    visitsCompleted: 4,
    visitsScheduled: 2,
    state: 'In Progress',
    status: 'Active',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['SLP'],
    notes: [
      { id: 'n10a', text: 'Speech therapy for post-concussion syndrome', author: 'Dr. Li', timestamp: '2026-04-01T11:30:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '11',
    patient: { name: 'Gerald Washington', dob: '12/25/1958', mrn: 'MRN-00815-9927' },
    authNumber: '',
    payer: { name: 'Medicare', planId: '00901' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 0,
    visitsScheduled: 2,
    state: 'Not Started',
    status: 'Needs Auth',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'New'],
    notes: [
      { id: 'n11a', text: 'New patient referral from Dr. Park - lumbar stenosis', author: 'Jaime Mandela', timestamp: '2026-04-19T08:45:00' },
    ],
  },
  {
    id: '12',
    patient: { name: 'Sofia Ramirez', dob: '05/11/1993', mrn: 'MRN-00422-6651' },
    authNumber: 'AUTH-AET_7790',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '2/01',
    endDate: '4/01',
    visitsAuthorized: 18,
    visitsCompleted: 18,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['OT', 'Follow-up'],
    notes: [
      { id: 'n12a', text: 'All visits completed, discharge summary sent', author: 'Sarah Adams', timestamp: '2026-03-30T16:00:00' },
      { id: 'n12b', text: 'Patient requests renewal for continued care', author: 'Emma Smith', timestamp: '2026-04-02T10:15:00' },
    ],
  },
  {
    id: '13',
    patient: { name: 'Sofia Ramirez', dob: '05/11/1993', mrn: 'MRN-00422-6651' },
    authNumber: 'AUTH-AET_8812',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '4/05',
    endDate: '6/05',
    visitsAuthorized: 20,
    visitsCompleted: 3,
    visitsScheduled: 2,
    state: 'Authorized',
    status: 'Active',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['OT'],
    notes: [
      { id: 'n13a', text: 'Renewal approved - continued OT for hand therapy', author: 'Emma Smith', timestamp: '2026-04-05T09:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '14',
    patient: { name: 'James O\'Brien', dob: '08/30/1980', mrn: 'MRN-00533-7742' },
    authNumber: 'AUTH-BCBS_2201',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '3/15',
    endDate: '5/15',
    visitsAuthorized: 25,
    visitsCompleted: 10,
    visitsScheduled: 3,
    state: 'Pending Payer Response',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Review'],
    notes: [
      { id: 'n14a', text: 'Extension request submitted for additional 10 visits', author: 'Jaime Mandela', timestamp: '2026-04-12T13:30:00' },
      { id: 'n14b', text: 'BCBS requested updated plan of care', author: 'Jaime Mandela', timestamp: '2026-04-14T09:00:00' },
      { id: 'n14c', text: 'Updated POC faxed to BCBS', author: 'Jon Jones', timestamp: '2026-04-14T15:45:00' },
    ],
    confidence: 'Pending',
  },
  {
    id: '15',
    patient: { name: 'Nadia Al-Farsi', dob: '01/14/1988', mrn: 'MRN-00667-3318' },
    authNumber: 'AUTH-CIG_4456',
    payer: { name: 'Cigna', planId: '00187' },
    startDate: '4/10',
    endDate: '6/10',
    visitsAuthorized: 12,
    visitsCompleted: 2,
    visitsScheduled: 1,
    state: 'Authorized',
    status: 'Active',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['SLP', 'New'],
    notes: [
      { id: 'n15a', text: 'Voice therapy - vocal cord dysfunction dx', author: 'Dr. Li', timestamp: '2026-04-10T10:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '16',
    patient: { name: 'Thomas Greene', dob: '04/09/1975', mrn: 'MRN-00891-2204' },
    authNumber: 'AUTH-MED_5510',
    payer: { name: 'Medicare', planId: '00901' },
    startDate: '1/20',
    endDate: '3/20',
    visitsAuthorized: 10,
    visitsCompleted: 10,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT'],
    notes: [
      { id: 'n16a', text: 'Completed all visits for rotator cuff repair rehab', author: 'Jon Jones', timestamp: '2026-03-18T11:00:00' },
    ],
  },
  {
    id: '17',
    patient: { name: 'Thomas Greene', dob: '04/09/1975', mrn: 'MRN-00891-2204' },
    authNumber: '',
    payer: { name: 'Medicare', planId: '00901' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 0,
    visitsScheduled: 1,
    state: 'Auth Requested',
    status: 'Needs Auth',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'Urgent'],
    notes: [
      { id: 'n17a', text: 'Re-injury reported, new auth needed for additional PT', author: 'Jon Jones', timestamp: '2026-04-20T08:30:00' },
    ],
    confidence: 'Pending',
  },
  {
    id: '18',
    patient: { name: 'Elena Volkov', dob: '10/22/1995', mrn: 'MRN-00934-5567' },
    authNumber: 'AUTH-UHC_6681',
    payer: { name: 'UHC', planId: '00445' },
    startDate: '3/25',
    endDate: '5/25',
    visitsAuthorized: 15,
    visitsCompleted: 7,
    visitsScheduled: 2,
    state: 'In Progress',
    status: 'Active',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['OT'],
    notes: [
      { id: 'n18a', text: 'Carpal tunnel rehab - splint fitted', author: 'Sarah Adams', timestamp: '2026-03-25T10:15:00' },
      { id: 'n18b', text: 'Patient reporting improvement in grip strength', author: 'Sarah Adams', timestamp: '2026-04-08T14:30:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '19',
    patient: { name: 'Derek Williams', dob: '06/01/1969', mrn: 'MRN-01022-8890' },
    authNumber: 'AUTH-AET_3320',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '4/15',
    endDate: '6/15',
    visitsAuthorized: 20,
    visitsCompleted: 1,
    visitsScheduled: 3,
    state: 'Authorized',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT', 'New'],
    notes: [
      { id: 'n19a', text: 'New eval completed - total hip replacement rehab', author: 'Jon Jones', timestamp: '2026-04-15T09:30:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '20',
    patient: { name: 'Priya Sharma', dob: '03/18/2003', mrn: 'MRN-01105-4421' },
    authNumber: 'AUTH-BCBS_9903',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '2/10',
    endDate: '4/10',
    visitsAuthorized: 18,
    visitsCompleted: 16,
    visitsScheduled: 0,
    state: 'Authorized',
    status: 'Expired',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['SLP', 'Follow-up'],
    notes: [
      { id: 'n20a', text: 'Fluency therapy program nearly complete', author: 'Dr. Li', timestamp: '2026-04-08T11:00:00' },
      { id: 'n20b', text: 'Discharged - goals met', author: 'Dr. Li', timestamp: '2026-04-10T16:00:00' },
    ],
  },
  {
    id: '21',
    patient: { name: 'Carmen Ruiz', dob: '11/29/1982', mrn: 'MRN-01210-3378' },
    authNumber: '',
    payer: { name: 'Humana', planId: '00556' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 1,
    visitsScheduled: 0,
    state: 'Not Started',
    status: 'Needs Auth',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Jaime Mandela',
    tags: ['OT', 'Urgent'],
    notes: [
      { id: 'n21a', text: 'Eval completed - awaiting auth before scheduling follow-ups', author: 'Sarah Adams', timestamp: '2026-04-17T13:00:00' },
    ],
  },
  {
    id: '22',
    patient: { name: 'Andre Mitchell', dob: '07/04/1971', mrn: 'MRN-01344-6609' },
    authNumber: 'AUTH-HUM_2278',
    payer: { name: 'Humana', planId: '00556' },
    startDate: '3/20',
    endDate: '4/20',
    visitsAuthorized: 8,
    visitsCompleted: 7,
    visitsScheduled: 1,
    state: 'Authorized',
    status: 'Expiring Soon',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['PT'],
    notes: [
      { id: 'n22a', text: 'ACL rehab - phase 2 complete, entering phase 3', author: 'Jon Jones', timestamp: '2026-04-10T10:00:00' },
      { id: 'n22b', text: 'Extension request being prepared - 1 visit remaining', author: 'Jaime Mandela', timestamp: '2026-04-18T14:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '23',
    patient: { name: 'Helen Park', dob: '02/14/1960', mrn: 'MRN-01489-1155' },
    authNumber: 'AUTH-MED_7741',
    payer: { name: 'Medicare', planId: '00901' },
    startDate: '4/01',
    endDate: '5/30',
    visitsAuthorized: 20,
    visitsCompleted: 6,
    visitsScheduled: 2,
    state: 'In Progress',
    status: 'Active',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['PT', 'Post-Op'],
    notes: [
      { id: 'n23a', text: 'Total knee replacement - 3 weeks post-op', author: 'Sarah Adams', timestamp: '2026-04-01T09:00:00' },
      { id: 'n23b', text: 'ROM improving, patient tolerating exercises well', author: 'Sarah Adams', timestamp: '2026-04-15T11:30:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '24',
    patient: { name: 'Kevin Nguyen', dob: '08/12/1997', mrn: 'MRN-01567-8834' },
    authNumber: 'AUTH-BCBS_1147',
    payer: { name: 'BCBS', planId: '00621' },
    startDate: '3/05',
    endDate: '5/05',
    visitsAuthorized: 22,
    visitsCompleted: 15,
    visitsScheduled: 3,
    state: 'Authorized',
    status: 'Expiring Soon',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['SLP', 'Review'],
    notes: [
      { id: 'n24a', text: 'Cognitive-linguistic therapy post TBI', author: 'Dr. Li', timestamp: '2026-03-05T10:00:00' },
      { id: 'n24b', text: 'Progress review scheduled with care team', author: 'Emma Smith', timestamp: '2026-04-16T09:00:00' },
      { id: 'n24c', text: 'Extension may be needed - nearing visit limit', author: 'Dr. Li', timestamp: '2026-04-19T15:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '25',
    patient: { name: 'Rachel Foster', dob: '12/03/1987', mrn: 'MRN-01698-2247' },
    authNumber: 'AUTH-CIG_5523',
    payer: { name: 'Cigna', planId: '00187' },
    startDate: '1/10',
    endDate: '3/10',
    visitsAuthorized: 14,
    visitsCompleted: 14,
    visitsScheduled: 0,
    state: 'Archived',
    status: 'Expired',
    facility: 'Riverside Clinic',
    provider: 'Sarah Adams',
    assignedTo: 'Emma Smith',
    tags: ['PT'],
    notes: [
      { id: 'n25a', text: 'Treatment complete - patient discharged to HEP', author: 'Sarah Adams', timestamp: '2026-03-10T12:00:00' },
    ],
  },
  {
    id: '26',
    patient: { name: 'Omar Hassan', dob: '05/26/1978', mrn: 'MRN-01802-9913' },
    authNumber: 'AUTH-HUM_3391',
    payer: { name: 'Humana', planId: '00556' },
    startDate: '4/08',
    endDate: '6/08',
    visitsAuthorized: 16,
    visitsCompleted: 3,
    visitsScheduled: 2,
    state: 'Authorized',
    status: 'Active',
    facility: 'Sunnybrook Hospital',
    provider: 'Jon Jones',
    assignedTo: 'Jaime Mandela',
    tags: ['OT', 'New'],
    notes: [
      { id: 'n26a', text: 'Work injury - right shoulder impingement OT program', author: 'Jon Jones', timestamp: '2026-04-08T08:00:00' },
    ],
    confidence: 'Confirmed',
  },
  {
    id: '27',
    patient: { name: 'Brittany Cole', dob: '09/15/1992', mrn: 'MRN-01956-4480' },
    authNumber: '',
    payer: { name: 'Aetna', planId: '00332' },
    startDate: '',
    endDate: '',
    visitsAuthorized: 0,
    visitsCompleted: 0,
    visitsScheduled: 1,
    state: 'Auth Requested',
    status: 'Needs Auth',
    facility: 'Westside Rehab',
    provider: 'Dr. Li',
    assignedTo: 'Emma Smith',
    tags: ['SLP', 'Urgent'],
    notes: [
      { id: 'n27a', text: 'Swallowing eval referral from ENT - auth submitted 4/19', author: 'Emma Smith', timestamp: '2026-04-19T16:30:00' },
    ],
    confidence: 'Pending',
  },
];
